Threads: 1
InPrefix: "images/Original/"
OutPrefix: "images/Website/"
InFolder: Original
OutFolder: a/bc/defgh/ijklmnop
Nonce: "0"
Plausibility: true
ServerAddr: :40715
SecretKey: super-secret-and-unguessable
LastCompletion: 0
